# -*- coding: utf-8 -*-
"""Built in collection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16IqQgiTw4JH8PBHJRWvPDVgr_BScKUuT

Dictionary(dict)
"""

student = {"name": "Hari", "age": 22}

print(len(student))          # 2 → number of keys
print(list(student.keys()))  # ['name', 'age']
print(list(student.values()))# ['Hari', 22]
print(student.get("name"))   # 'Hari'
print(student.items())       # dict_items([('name','Hari'), ('age',22)])
print("age" in student)      # True
student.update({"age": 23})  # change value
student.pop("name")          # remove key

"""List(list)"""

fruits = ["apple", "banana", "cherry"]

print(len(fruits))           # 3
print(max(fruits))           # 'cherry' (alphabetical order)
print(min(fruits))           # 'apple'
print(sorted(fruits))        # ['apple','banana','cherry']
fruits.append("grape")       # add element
fruits.remove("banana")      # remove element
print(fruits.index("apple")) # 0
print(fruits.count("apple")) # 1
fruits.reverse()             # reverse order

"""Set(set)"""

numbers = {1, 2, 3, 4}

print(len(numbers))          # 4
print(max(numbers))          # 4
print(min(numbers))          # 1
print(2 in numbers)          # True
numbers.add(5)               # add element
numbers.remove(3)            # remove element
print(numbers.union({6,7}))  # {1,2,4,5,6,7}
print(numbers.intersection({2,5,8})) # {2,5}
print(numbers.difference({1,5}))     # {2,4}

"""Tuple(tuple)"""

data = (10, 20, 30, 20)

print(len(data))             # 4
print(max(data))             # 30
print(min(data))             # 10
print(data.count(20))        # 2
print(data.index(30))        # 2
print(20 in data)            # True

"""String(str)"""

text = "Hariharan"
print(len(text))        # 9
print(text.upper())     # "HARIHARAN"
print(text.lower())     # "hariharan"
print(text.split("a"))  # ['H', 'rih', 'r', 'n']
print("Hari" in text)   # True