# -*- coding: utf-8 -*-
"""Miniproject_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nuQlkA1o41QUl5zdM72qt6Y4FEI_5nUB
"""

contacts = {}

def add_contact():
    name = input("Enter contact name: ")
    phone = input("Enter 10-digit phone number: ")

    if len(phone) != 10 or not phone.isdigit():
        print(" Invalid phone number! Must be 10 digits.")
        return

    if phone in [p for _, p in contacts.values()]:
        print(" This phone number already exists!")
        return

    # Store lowercase key, but keep original name for display
    contacts[name.lower()] = (name, phone)
    print(f" Contact '{name}' added successfully!")

def search_contact():
    name = input("Enter name to search: ")
    key = name.lower()
    if key in contacts:
        original_name, phone = contacts[key]
        print(f"{original_name}: {phone}")
    else:
        print(" Contact not found.")

def delete_contact():
    name = input("Enter name to delete: ")
    key = name.lower()
    if key in contacts:
        original_name, _ = contacts[key]
        del contacts[key]
        print(f" Contact '{original_name}' deleted successfully!")
    else:
        print(" Contact not found.")

def display_contacts():
    if not contacts:
        print(" No contacts available.")
    else:
        print(" All Contacts:")
        for original_name, phone in contacts.values():
            print(f"- {original_name}: {phone}")

while True:
    print("\n--- Contact Book Menu ---")
    print("1. Add Contact")
    print("2. Search Contact")
    print("3. Delete Contact")
    print("4. Display All Contacts")
    print("5. Exit")

    choice = input("Enter your choice (1-5): ")

    match choice:
        case "1":
            add_contact()
        case "2":
            search_contact()
        case "3":
            delete_contact()
        case "4":
            display_contacts()
        case "5":
            print(" Exiting Contact Book. Goodbye!")
            break
        case _:
            print(" Invalid choice. Please try again.")

