# -*- coding: utf-8 -*-
"""miniproject_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBfIvCV1vHw9KhH0BCO_LXEozm_N_S6V
"""

def word_frequency_counter(paragraph):
    paragraph = paragraph.lower()
    for ch in ".,!?;:":
        paragraph = paragraph.replace(ch, "")
    words = paragraph.split()
    freq = {}
    for word in words:
        freq[word] = freq.get(word, 0) + 1
    print("\n--- Words Appearing Exactly 3 Times ---\n")
    found = False
    for word, count in freq.items():
        if count == 3:
            print(word, "->", count)
            found = True
    if not found:
        print("No words appeared exactly 3 times.")
paragraph = input("Enter a paragraph: ")
word_frequency_counter(paragraph)