# -*- coding: utf-8 -*-
"""miniproject_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBfIvCV1vHw9KhH0BCO_LXEozm_N_S6V
"""

def word_frequency_counter(paragraph):
    paragraph = paragraph.lower()
    for ch in ".,!?;:":
        paragraph = paragraph.replace(ch, "")
    words = paragraph.split()

    freq = {}
    for word in words:
        freq[word] = freq.get(word, 0) + 1

    while True:
        target_count = int(input("\nEnter Count (0 to exit): "))
        if target_count == 0:
            print("Exiting program... Goodbye!")
            break

        print(f"\n--- Words Appearing Exactly {target_count} Times ---\n")
        found = False
        for word, word_count in freq.items():
            if word_count == target_count:
                print(word, "->", word_count)
                found = True

        if not found:
            print(f"No words appeared exactly {target_count} times.")

paragraph = input("Enter a paragraph: ")
word_frequency_counter(paragraph)

