# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IuDfv0yQJkXYvSf8b8AYWtPZOchjN47X

1.Write a function is_prime(n) that takes a number and returns True if it's prime, False otherwise. Use it to print all prime numbers between 1 and 50.
"""

def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True
for num in range(1, 50):
    if is_prime(num):
        print(num)

"""2.Write a function calculate_bill(item, price, quantity=1, discount=0) that calculates the total bill for an item (price x quantity, minus discount%). Call it three times: once using only positional arguments, once using keyword arguments in a different order, and once relying on the default quantity and discount values."""

def calculate_bill(item, price, quantity=1, discount=0):
    total = price * quantity
    total -= total * (discount / 100)
    return total
print("Notebook:", calculate_bill("Notebook", 50, 3, 10))
print("Headphones:", calculate_bill(price=200, discount=5, item="Headphones", quantity=2))
print("Pen:", calculate_bill("Pen", 10))

"""3.Write a lambda function that takes a number and returns its square. Use it to print the square of 5 different numbers of your choice."""

def square(n):
    return n ** 2
print(square(2))
print(square(5))
print(square(7))
print(square(10))
print(square(12))

"""4.Write a recursive function fibonacci(n) that returns the nth Fibonacci number (0, 1, 1, 2, 3, 5, 8...). Use it to print the first 10 Fibonacci numbers. Clearly identify the base case and recursive case in a comment."""

def fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacci(n-1) + fibonacci(n-2)
for i in range(10):
    print(fibonacci(i))

"""5.Write an outer function make_multiplier(factor) that defines and returns an inner function multiply(x), which multiplies x by factor. Use make_multiplier to create two separate functions — double (factor=2) and triple (factor=3) — and demonstrate both by calling them with a few numbers."""

def mmm(factor):
    def multiply(x):
        return x * factor
    return multiply
double = mmm(2)
triple = mmm(3)
print("Double of 5:", double(5))
print("Double of 12:", double(12))
print("Triple of 4:", triple(4))
print("Triple of 7:", triple(7))