# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GQ3eMAc_14hoIHwyOWfeEv1YyIyzLB08

Bug 1 — Type Casting Expected: Should print Next year you'll be 26
"""

age = 25
print("Next year you'll be",age + 1)

"""Bug 2 — Comparison Operators Expected: Should print x is five"""

x = 5
if x == 5:
    print("x is five")

"""Bug 3 — if / elif / else Expected: grade(95) should print only A"""

def grade(marks):
    if marks >= 90:
        print("A")
    elif marks >= 75:
        print("B")
    elif marks >= 50:
        print("C")
    else:
        print("F")

grade(95)

"""Bug 4 — match-case Expected: Should print Stopping..."""

command = "stop"

match command:
    case "start":
        print("Starting...")
    case "stop":
        print("Stopping...")
    case _:
        print("Unknown command")

"""Bug 5 — for Loop & range() Expected: Should print Sum of 1 to 10: 55"""

total = 0
for i in range(1, 11):
    total += i
print("Sum of 1 to 10:", total)

"""Bug 6 — while Loop       Expected: Should print 1, 2, 3, 4, 5 (one per line) and then stop"""

count = 1
while count <= 5:
    print(count)
    count += 1

"""Bug 7 — break vs continue Expected: Should print 1, 2, 4, 5 (skipping only 3), then for i in range(1, 6): if i == 3: break print(i) print("Loop finished")"""

for i in range(1, 6):
    if i == 3:
        continue
    print(i)
print("Loop finished")

"""Bug 8 — Functions & return Expected: Should print def add(a, b): print(a + b) Result: 30"""

def add(a, b):
    return a + b
result = add(5, 10)
print("Result:", result * 2)

"""Bug 9 — *args Expected: total_sum(1, 2, 3, 4) should print 10"""

def total_sum(*args):
    total = 0
    for num in args:
        total += num
    return total
print(total_sum(1, 2, 3, 4))

"""ug 10 — Recursion Expected: factorial(5) should print 120"""

def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n - 1)
print(factorial(5))

"""Bug 11 — Variables Expected: Should print  10 5 (a and b swapped)"""

a = 5
b = 10
a,b = b,a
print(a,b)

"""Bug 12 — Data Types Expected: Should print equal"""

num = "10"
if int(num) == 10:
    print("Equal")
else:
    print("Not equal")

"""Bug 13 — Operators    
Expected: Should print Average: 3.4
"""

total = 17
count = 5
average = total / count
print("Average:", average)

"""Bug 14 — print() Expected: Should print Name: Alice Age: 21"""

name = "Alice"
age = 21

print("Name:", name, "Age:", age)

"""Bug 15 — Keywords Expected: Should print Python 101"""

name = "Python 101"
print(name)

"""Bug 16 — for Loop Expected: Should print 60 (sum of the list)"""

numbers = [10, 20, 30]
total = 0
for num in numbers:
  total += num
print(total)

"""Bug 17 — while Loop Expected: Should print 'Withdrawing...' three times, then Final balance: 10 3/5"""

balance = 100
while balance > 10:
    print("Withdrawing...")
    balance -= 30
print("Final balance:", balance)

"""Bug 18 — Default Arguments  Expected: Should print ['apple'] then ['banana'] (two separate, independent carts)"""

def add_item(item, cart=[]):
    cart.append(item)
    return cart
print(add_item("apple"))
print(add_item("banana"))

"""Bug 19 — Lambda  Expected: Should print 25"""

multiply = lambda a, b: a * b
print(multiply(5, 5))

"""Bug 20
 Expected: Should print 15 (5 multiplied by 3)
"""

num = "5"
result = num * 3
print(result)

"""Bug 21 — Default Arguments Expected: add_to_x(5) should print 25 , using the updated value of x (20)"""

# x = 10
def add_to_x(n, value=x):
  return n + value
  x = 20
print(add_to_x(5))

"""Bug 22 — Recursion  Expected: sum_to_n(5) should print 15 (5+4+3+2+1)"""

def sum_to_n(n):
  if n == 0:
     return 0
  return sum_to_n(n - 1) + n
print(sum_to_n(5))

"""Bug 23 — Parameters   Expected: Should print Alice 25 NYC"""

def describe(name, age, city):
  print(name, age, city)
describe("Alice", 25, "NYC")

"""Bug 24 — match-case Expected: Should print The answer!"""

value = 42
match value:
  case 42:
    print("It's an integer")
  case int():
    print("The answer!")

