# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BC-2hbO0eSYEtK70n28BLHlGOhwiaCP5
"""

#1
name = "Hariharan"
age = 22
city = "Bengaluru"
print(f"My name is {name}, I am {age} years old, and I live in {city}.")

#2
a = 5
b = 10
a, b = b, a
print("After swapping: a =", a, "b =", b)

# 3
num_int = 42
num_float = 3.14
text_str = "Python"
flag_bool = True
print(num_int, "is", type(num_int))
print(num_float, "is", type(num_float))
print(text_str, "is", type(text_str))
print(flag_bool, "is", type(flag_bool))

#4
x = 10
y = "10"

print(type(x))
print(type(y))

# 5
num1 = "25"
num2 = "30.5"
num1_int = int(num1)
num2_float = float(num2)
result = num1_int + num2_float
print("The sum is:", result)

# 6
weight_kg = input("Enter your weight in kilograms: ")
weight_kg = float(weight_kg)
weight_lbs = weight_kg * 2.205
print("Your weight in pounds is:", weight_lbs)

#7
'''
This program demonstrates how to convert string values into numeric types
(int and float), perform addition on them, and print the result.
'''
num1 = "25"
num2 = "30.5"
num1_int = int(num1)
num2_float = float(num2)
print("The sum is:", num1_int + num2_float)

"""if → Used for conditional branching (executes code if condition is true).

else → Provides an alternative block if the if condition is false.

elif → Short for "else if"; checks another condition if the previous one fails.

import → Brings in external modules or libraries into your program.

True → Boolean constant representing truth.

False → Boolean constant representing falsehood.

try → Starts a block of code to test for exceptions.

except → Defines a block of code to run if an exception occurs.

finally → Runs code regardless of whether an exception occurred.

yield → Used inside a function to create a generator (returns values one at a time).
"""

#9
for = 5

