# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13C6eiISu1IL-Ljq9wgzKwz_o14Aqvh8E

1.Write a program that takes a sentence as input and prints: the number of vowels in it, the sentence reversed, and the sentence in uppercase.
"""

def ps(sentence):
    vowels = "aeiouAEIOU"
    vowel_count = sum(1 for char in sentence if char in vowels)
    reversed_sentence = sentence[::-1]
    uppercase_sentence = sentence.upper()
    print("Number of vowels:", vowel_count)
    print("Reversed sentence:", reversed_sentence)
    print("Uppercase sentence:", uppercase_sentence)
user_input = input("Enter a sentence: ")
ps(user_input)

"""2.Write a program that takes a list of numbers and creates a new list containing only the squares of the even numbers, using list comprehension."""

def even_squares(numbers):
    return [n**2 for n in numbers if n % 2 == 0]
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
result = even_squares(nums)
print("Original list:", nums)
print("Squares of even numbers:", result)

"""3.Write a program that stores the (name, marks) of 5 students as a list of tuples, then prints the name of the student with the highest marks."""

students = [("Hari", 85),("Rohit", 92),("Jithendra", 78),("Arya", 95),("Nandhana", 88)]
top_student = max(students, key=lambda x: x[1])
print("Student with highest marks:", top_student[0])

"""4.Write a program that takes two lists of student names (Section A and Section B) and prints: students in both sections, students only in Section A, and students only in Section B."""

def comp(section_a, section_b):
    both = [student for student in section_a if student in section_b]
    only_a = [student for student in section_a if student not in section_b]
    only_b = [student for student in section_b if student not in section_a]
    print("Students in both sections:", both)
    print("Students only in Section A:", only_a)
    print("Students only in Section B:", only_b)
section_a = ["Alice", "Bob", "Charlie", "David"]
section_b = ["Charlie", "David", "Eva", "Frank"]
comp(section_a, section_b)

"""5.Write a program that stores at least 5 products with their prices in a dictionary, then prints all product names whose price is greater than 100, using .items().

"""

products = {"Notebook": 50,"Headphones": 200,"Keyboard": 120,"Mouse": 80,"Monitor": 300}
print("Products with price greater than 100:")
for name, price in products.items():
    if price > 100:
        print(name)

