# -*- coding: utf-8 -*-
"""WordFrequencyCounter_Miniproject_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ibZkW5NB7D0LF6K5u3zHVHjKE8ttkQLA
"""

def word_frequency_counter(paragraph):
    paragraph = paragraph.lower()
    for ch in ".,!?;:":
        paragraph = paragraph.replace(ch, "")
    words = paragraph.split()
    freq = {}
    for word in words:
        if word in freq:
            freq[word] += 1
        else:
            freq[word] = 1
    sorted_freq = sorted(freq.items(), key=lambda x: x[1], reverse=True)
    top_three = sorted_freq[:3]
    print("\n--- Top 3 Most Common Words ---\n")
    for word, count in top_three:
        print(word, "->", count)

paragraph = input("Enter a paragraph: ")
word_frequency_counter(paragraph)

