# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10U05pJjVEY03pQuaEILnZ8O5Z_KA1FFH
"""

# 1(a)
num = int(input("Enter a number: "))
if num % 2 == 0:
    print(f"{num} is Even")
else:
    print(f"{num} is Odd")

# 1(b)
marks = int(input("Enter your marks: "))
if marks >= 40:
    print("Pass")
else:
    print("Fail")

# 2(a)
num = int(input("Enter a number: "))
if num > 0:
    print("Positive")
elif num < 0:
    print("Negative")
else:
    print("Zero")

# 2(b)
age = int(input("Enter your age: "))
if 0 <= age <= 12:
    print("Child")
elif 13 <= age <= 19:
    print("Teenager")
elif 20 <= age <= 59:
    print("Adult")
elif age >= 60:
    print("Senior")
else:
    print("Invalid age")

# 3(a)
um = int(input("Enter a number: "))
if num > 0:
    print("The number is Positive")
    if num % 2 == 0:
        print("It is Even")
    else:
        print("It is Odd")
else:
    print("The number is not Positive")

# 3(b)
age = int(input("Enter your age: "))
logged_in = input("Are you logged in? (True/False): ")
if age >= 18:
    if logged_in == "True":
        print("Access granted")
    else:
        print("Access denied - not logged in")
else:
    print("Access denied - age below 18")

# 4(a)
marks = int(input("Enter marks: "))
result = "Pass" if marks >= 35 else "Fail"
print(result)

# 4(b)
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
larger = a if a > b else b
print("Larger number is:", larger)

# 5(a)
day = int(input("Enter day number (1-7): "))
match day:
    case 1:
        print("Monday")
    case 2:
        print("Tuesday")
    case 3:
        print("Wednesday")
    case 4:
        print("Thursday")
    case 5:
        print("Friday")
    case 6:
        print("Saturday")
    case 7:
        print("Sunday")
    case _:
        print("Invalid day number")

# 5(b)
grade = input("Enter grade (A/B/C/Other): ")
match grade:
    case "A":
        print("Excellent")
    case "B":
        print("Good")
    case "C":
        print("Average")
    case _:
        print("Needs improvement")

# 6(a)
num = int(input("Enter a number: "))
for i in range(1, 11):
    print(f"{num} x {i} = {num * i}")

# 6(b)
total = 0
for i in range(1, 51):
    total += i
print("The sum is:", total)

# 7(a)
fruits = ["Apple", "Banana", "Cherry", "Mango", "Orange"]
for i in range(len(fruits)):
    print(f"Index {i}: {fruits[i]}")

# 7(b)
numbers = [10, -5, 7, -3, 12]
for i in range(len(numbers)):
    if numbers[i] < 0:
        numbers[i] = 0
print("Updated list:", numbers)

# 8(a)
i = 2
while i <= 20:
    print(i)
    i += 2

# 8(b)
correct_pasw= "python123"
pasw= ""
while pasw != correct_pasw:
    pasw= input("Enter password: ")
print("Access granted!")

# 9(a)
while True:
    user_input = input("Enter a number (or type 'exit' to stop): ")
    if user_input.lower() == "exit":
        break
    else:
        print("You entered:", user_input)
print("Program ended.")

# 9(b)
while True:
    print("\n--- Menu ---")
    print("1. Say Hello")
    print("2. Show a number square")
    print("3. Quit")
    choice = input("Enter your choice (1-3): ")
    if choice == "1":
        print("Hello, welcome!")
    elif choice == "2":
        num = int(input("Enter a number: "))
        print(f"The square of {num} is {num*num}")
    elif choice == "3":
        print("Exiting program... Goodbye!")
        break
    else:
        print("Invalid choice, try again.")

# 10(a)
n = int(input("Enter number of rows: "))
for i in range(1, n + 1):
    for j in range(i):
        print("*", end=" ")
    print()

# 10(b)
for i in range(1, 6):
    for j in range(1, 6):
        print(f"{i*j:3}", end=" ")
    print()

# 11(a)
numbers = [10, 25, 30, 45, 50]
target = int(input("Enter the number to search: "))
for num in numbers:
    if num == target:
        print(f"Found {target} in the list!")
        break
else:
    print("Target not found.")

# 11(b)
for i in range(1, 21):
    if i % 7 == 0:
        print(f"Stopping at {i}, divisible by 7")
        break
    print(i)

# 12(a)
for i in range(1, 16):
    if i % 3 == 0:
        continue
    print(i)

# 12(b)
names = ["Alice", "Bob", "Eve", "Charlie", "Oscar", "David"]
for name in names:
    if name[0].lower() in "aeiou":
        continue
    print(name)

