# -*- coding: utf-8 -*-
"""PhoneBook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cfRuYP3jdRxCsKTdiCsBU2979OU9X3Vw
"""

contacts = {}


def add_contact():
    name = input("Enter contact name: ")
    phone = input("Enter 10-digit phone number: ")

    if name == "":
        print("Name cannot be empty!")
        return

    if phone == "":
        print("Phone number cannot be empty!")
        return

    if not phone.isdigit() or len(phone) != 10:
        print("Invalid phone number!")
        return

    for contact in contacts.values():
        if contact[1] == phone:
            print("This phone number already exists!")
            return

    contacts[name.lower()] = (name, phone)

    print("Contact added successfully!")


def search_contact():
    name = input("Enter name to search: ")

    if name.lower() in contacts:
        name, phone = contacts[name.lower()]
        print("Name :", name)
        print("Phone:", phone)
    else:
        print("Contact not found!")


def delete_contact():
    name = input("Enter name to delete: ")

    if name.lower() in contacts:
        del contacts[name.lower()]
        print("Contact deleted successfully!")
    else:
        print("Contact not found!")


def display_contacts():
    if not contacts:
        print("No contacts available!")
        return

    for name, phone in contacts.values():
        print("Name :", name)
        print("Phone:", phone)
        print("----------------")


while True:
    print("\n--- Contact Book Menu ---")
    print("1. Add Contact")
    print("2. Search Contact")
    print("3. Delete Contact")
    print("4. Display All Contacts")
    print("5. Exit")

    choice = input("Enter your choice: ")

    match choice:
        case "1":
            add_contact()

        case "2":
            search_contact()

        case "3":
            delete_contact()

        case "4":
            display_contacts()

        case "5":
            print("Exit")
            break

        case _:
            print("Invalid choice!")