# -*- coding: utf-8 -*-
"""wordfreqcounter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10f_yePnhNB_-izcczpUCpGF--BOJ9aXU
"""

def word_frequency_counter(paragraph, target_count):

    paragraph = paragraph.lower()

    words = paragraph.split()

    freq = {}

    for word in words:
        freq[word] = freq.get(word, 0) + 1

    print(f"\n--- Words Appearing Exactly {target_count} Times ---\n")

    found = False

    for word, word_count in freq.items():
        if word_count == target_count:
            print(word, "->", word_count)
            found = True

    if not found:
        print(f"No words appeared exactly {target_count} times.")


paragraph = input("Enter a paragraph: ")

target_count = int(input("Enter Count Here: "))

word_frequency_counter(paragraph, target_count)