# -*- coding: utf-8 -*-
"""wordfreqcounter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BCxFw7wCJg1GqSK8Bhq-ro-1q2dMfbR0
"""

def word_frequency_counter(paragraph):

    paragraph = paragraph.lower()

    words = paragraph.split()

    frequency = {}

    for word in words:
        if word in frequency:
            frequency[word] += 1
        else:
            frequency[word] = 1

    sorted_words = sorted(frequency.items(), key=lambda x: x[1], reverse=True)

    top_three = sorted_words[:3]

    print("\n--- Top 3 Most Common Words ---")

    for word, count in top_three:
        print(word, "->", count)


paragraph = input("Enter a paragraph: ")

word_frequency_counter(paragraph)