# -*- coding: utf-8 -*-
"""assigments.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e6iK1rrYjAbprTUslmKcSeJ4AK6sioCS
"""

a='jithendra'
b=22
c='machilipatnam'
print("name is "+a+"age" +str(b)+ "city" +c)

#2
A=20
B=30
# using tuple
A,B=B,A
print(f"A:{A},B:{B}")

#3
int_a=20
float_b=20.15
str_c="vijay"
is_active=True
print(a)
print(b)
print(c)
print(is_active)

#3
X=10
Y="10"
B='5'
#any thing in single qots and double qots is string

print(type(X))
print(type(Y))
print(type(B))

A="25"
B="30.5"
A=(int(A))
B=(float(B))
print(type(A))
print(type(B))
print(A+B)

#4
user=input("Enter their weight in kgs:")
user=(float(user))
print(user+2.205," lbs")

# Prompt the user to enter their name and store it in a variable
name = input("Enter your name: ")

# Prompt the user for their birth year
# Use int() to cast the input string into an integer for calculations
birth_year = int(input("Enter your birth year: "))

# Set the current year as a constant
CURRENT_YEAR = 2026

# Calculate approximate age by subtracting the birth year from the current year
age = CURRENT_YEAR - birth_year

# Print a formatted greeting message including the user's name and calculated age
print(f"Hello {name}, you are approximately {age} years old.")

# Loop through numbers from 1 to 15 inclusive
for i in range(1, 16):
    # Check if the number is divisible by 3
    if i % 3 == 0:
        # Skip the rest of the current loop iteration
        continue
    # Print the number if it is not a multiple of 3
    print(i)

# Define a list of names to iterate through
names = ["Alice", "Bob", "Charlie", "Elena", "Ian", "David", "Omar", "Ursula", "Frank"]

# Define a tuple of lowercase vowels for checking
vowels = ("a", "e", "i", "o", "u")

# Loop through each name in the list
for name in names:
    # Check if the lowercase version of the first letter is a vowel
    if name[0].lower() in vowels:
        # Skip the rest of the loop iteration for this name
        continue
    # Print the name if it does not start with a vowel
    print(name)