# -*- coding: utf-8 -*-
"""control satements.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UX_SeEt_sF09U4tyBhWS36D3qUKHV0GW
"""

#control statements
a=input("enter the number:")
if int(a) %2==0:
 print("it is even number")
else:
 print("odd number")

a=input("marks:")
if int(a)>=40:
  print("pass")
else:
  print("fail")

number=input("take a number:")
if int(number) >0:
  print("postive numnber")
elif int(number) <0:
  print("neagtive number")
else:
  print("its zero")

age=input("enter the age:")
if int(age) <=12:
  print("child")
elif int(age) <=19:
  print("teenager")
elif int(age) <=59:
  print("adult")
else:
  print("senior")

num=input("enter the number:")
if int(num)  >0:
  print("positive number")
else:
  print("neagtive number")
  if int(num) %2==0:
    print("even number")
  else:
    print("odd number")

age=input("enter the age:")
login_input = input("Are you logged in? (true/false):")
is_logged_in = True if login_input.lower() == "true" else False
if int(age) >= 18 and is_logged_in:
 print("acess granted")
else:
  print("no acess")

marks=int(input())
s="pass" if marks >=35 else "fail"
print(s)

a=int(input())
b=int(input())
print(a if a>b else b)

num=int(input("Enter a number (1-7) for the day of the week:"))

match num:
    case 1:
        print("Sunday")
    case 2:
        print("Monday")
    case 3:
        print("Tuesday")
    case 4:
        print("Wednesday")
    case 5:
        print("Thursday")
    case 6:
        print("Friday")
    case 7:
        print("Saturday")
    case _:
        print("Invalid number. Please enter a number between 1 and 7.")

grade=input("enter the grade:")
match grade:
  case "A":
    print("excellent")
  case "B":
    print("very good")
  case "C":
    print("good")
  case "d":
    print("average")
  case "e":
    print("pass")

num=int(input("enter the number:"))
for i in range(1,11):
    print(i*num )

total_sum=0
for i in range(1,51):
  total_sum=total_sum+i
print(total_sum)

a=["mango","banana","greaps"]
for i in range(len(a)):
  print(a[i])

a=[1,3,-4,-5,-10]
for i in range(len(a)):
 if a[i] <0:
   a[i]=0
   print(a)

num=0
while(num <20):
  num = num +1
  if num %2==0:
    print(num)

correct_password="divya"
user_input=input("enter the password: ")
while user_input != correct_password:
  print("wrong password")
  user_input=input("enter the password: ")
print("correct password")

while True:
  user_input=input("enter the number")
  if user_input =="exit":
    print("exxiting the loop-----")
    break
  print("your enterd " ,user_input)

while True:
    print("\n--- MENU ---")
    print("1. Option One")
    print("2. Option Two")
    print("3. Quit")

    choice = input("Enter choice (1-3): ").strip()

    if choice == "1":
        print("You selected Option One!")
    elif choice == "2":
        print("You selected Option Two!")
    elif choice == "3":
        print("Goodbye!")
        break
    else:
        print("Invalid choice. Please try again.")

for i in range(1,5):
 for j in range(i):
     print("*",end="")
 print()

for row in range(1, 6):
    for col in range(1, 6):
        print(row * col, end='\t')
    print()  # Move to the next line after each row