# -*- coding: utf-8 -*-
"""contact book-mini project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19L8UjedSwS3Gmg3wU8W8swVfFuLKEGcG
"""

d1={}
#adding contact
def add_contact():
  name = input("enter name:")
  phone_number = input("phone number:")
  d1[name] = phone_number
  print(f"Contact {name}: {phone_number}\n contact added successfully")
  print("Current contacts:", d1)
#add_contact()
#-----------searching contact----------
def search_contact():
  name=input("enter name:")
  if name in d1:
    print(f"Contact found \n {name}: {d1[name]}")
  else:
    print(f"Contact {name} not found")
#search_contact()
#--------------deleteing contact-------
def delete_contact():
  name=input("enter name:")
  if name in d1:
    # Retrieve phone number before deleting
    phone_number_to_delete = d1[name]
    del d1[name]
    print(f"deleted successfully {name}: {phone_number_to_delete}")
  else:
    print(f"contact {name} not found ")
#delete_contact()
#---------------list of thr conatacts--------
def list1_contacts():
  print("Current contacts:")
  if not d1:
    print("No contacts available.")
  else:
    for name, phone_number in d1.items():
      print(f"{name}: {phone_number}")
#list1_contacts()
#----------------switch cases-------------
while True:
  print("\n============ CONTACT BOOK============:")
  print("1. Add Contact")
  print("2. Search Contact")
  print("3. Delete Contact")
  print("4. List Contacts")
  print("5. Exit")
  choice=input("enter your choice:")
  match choice:
    case '1':
      add_contact()
    case '2':
      search_contact()
    case '3':
      delete_contact()
    case '4':
      list1_contacts()
    case '5':
      print("Exiting the contact book. Goodbye!")
      break
#------------or-------------------------
"""
  if choice == '1':
    add_contact()
  elif choice == '2':
    search_contact()
  elif choice == '3':
    delete_contact()
  elif choice == '4':
    list1_contacts()
  elif choice == '5':
    print("Exiting the contact book. Goodbye!")
    break
  else:
    print("Invalid choice. Please enter a number between 1 and 5.")
"""