# -*- coding: utf-8 -*-
"""functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_00Qtys8IC4YTOpRpM8Og2saiYxgDXQy
"""

def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Print all prime numbers between 1 and 50
primes = [n for n in range(1, 51) if is_prime(n)]
print(primes)

def calculate_bill(item, price, quantity=1, discount=0):
    total = price * quantity
    total_after_discount = total * (1 - discount / 100)
    return total_after_discount


# 1. Using only positional arguments
bill1 = calculate_bill("Book", 20, 3, 10)
print(f"Positional arguments: ${bill1:.2f}")

# 2. Using keyword arguments in a different order
bill2 = calculate_bill(discount=15, item="Headphones", quantity=2, price=50)
print(f"Keyword arguments (reordered): ${bill2:.2f}")

# 3. Relying on default values for quantity (1) and discount (0)
bill3 = calculate_bill("Laptop", 1000)
print(f"Default values used: ${bill3:.2f}")

square = lambda x: x**2

numbers = [3, 7, 12, 15, 20]
for num in numbers:
    print(f"The square of {num} is {square(num)}")

def fibonacci(n):
    # Base case: return 0 for n=0, and 1 for n=1
    if n <= 0:
        return 0
    elif n == 1:
        return 1

    # Recursive case: sum of the two preceding numbers
    return fibonacci(n - 1) + fibonacci(n - 2)


# Print the first 10 Fibonacci numbers (n = 0 to 9)
for i in range(10):
    print(fibonacci(i), end=" " if i < 9 else "\n")

def make_multiplier(factor):
    def multiply(x):
        return x * factor

    return multiply


# Create double and triple functions
double = make_multiplier(2)
triple = make_multiplier(3)

# Demonstrate usage
numbers = [2, 5, 10]

print("Doubled values:")
for num in numbers:
    print(f"double({num}) = {double(num)}")

print("\nTripled values:")
for num in numbers:
    print(f"triple({num}) = {triple(num)}")