# -*- coding: utf-8 -*-
"""word frequency counter

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qsaFKuE_LJOpxfnvt6LxN3fa3p4vxMiX
"""

# 1. Take paragraph from user
paragraph = input("Enter a paragraph:\n")

# Clean the text (lowercase and simple punctuation removal)
paragraph = paragraph.lower()
for char in ".,!?":
    paragraph = paragraph.replace(char, "")

# 2. Split paragraph into individual words
words = paragraph.split()

# 3. Count each word using a dictionary
word_counts = {}
for word in words:
    if word in word_counts:
        word_counts[word] += 1
    else:
        word_counts[word] = 1

# 4. Sort words by count using standard sorted()
sorted_words = sorted(word_counts, key=word_counts.get, reverse=True)

# 5 & 6. Take top 3 and display result
print("\n--- Top 3 Most Common Words ---")

for word in sorted_words[:3]:
    print(f"{word} -> {word_counts[word]}")