# -*- coding: utf-8 -*-
"""word frequency -2-mini

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L5A9tYLs71UsVTehsSXnmq9Bb0m0--BV
"""

# 1. Get input text from the user
paragraph = input("Enter a paragraph:\n")

# 2. Convert to lowercase and clean simple punctuation
paragraph = paragraph.lower()
for char in ".,!?":
    paragraph = paragraph.replace(char, "")

# 3. Split into words
words = paragraph.split()

# 4. Count each word using a dictionary
word_counts = {}
for word in words:
    if word in word_counts:
        word_counts[word] = word_counts[word] + 1
    else:
        word_counts[word] = 1

# 5. Interactive loop to search by word count
while True:
    target_count = int(input("\nEnter Count (0 to exit): "))

    if target_count == 0:
        print("Exiting program... Goodbye!")
        break

    print(f"\n--- Words Appearing Exactly {target_count} Times ---")

    found = False
    for word, count in word_counts.items():
        if count == target_count:
            print(f"{word} -> {count}")
            found = True

    if not found:
        print(f"No words appeared exactly {target_count} times.")